port: 8080
server_shutdown_timeout_sec: 5
backends:
  - http://localhost:8001
  - http://localhost:8002
  - http://localhost:8003

# ниже настройки для ограничителя запросов
rate_limit:
  default:
    capacity: 10
    fill_rate: "1s"
  overrides:
    # это пример
    "192.168.1.1":
      capacity: 50
      fill_rate: "500ms"