port: 8080
server_shutdown_timeout_sec: 5
lb_method: "RR" # RR|LC
backends:
  - http://127.0.0.1:8001
  - http://127.0.0.1:8002
  - http://127.0.0.1:8003
rate_limit:
  enabled: true
  cleanup_interval: 1m
  default:
    requests_per_sec: 100
    burst: 200
  special_limits:
    - ips: []
      limit:
        requests_per_sec: 50
        burst: 100
